version: "3"
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /home/fsn/nutzerdatenbank-frontend:/project/:cached
        ports:
            - 4200:4200

networks:
  traefik_net:
    external: true