name: Deploy to Production

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Angular Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nutzerdatenbank-frontend:latest -f docker/prod/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nutzerdatenbank-frontend:latest
